# DeployWindowsClient.yml - A playbook that deploys a Windows 7 client in VCSA.
---
- hosts: localhost
  vars:
    path: "{{ esxi_datastore }}/Win7SP1Unattend.iso"
  tasks:
  - name: Deploy the Windows client
    vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      guest: "Windows 7 Client"
      state: powered_on
      vm_disk:
        disk1:
          size_gb: 80
          type: thin
          datastore: "{{ esxi_datastore }}"
          folder: "Windows 7 Client"
      vm_nic:
        nic1:
          type: e1000
          network: "VM Network"
          network_type: standard
      vm_hardware:
        memory_mb: 2048
        num_cpus: 1
        osid: windows7_64guest
        scsi: "lsi_sas"
        vm_cdrom:
          type: "iso"
          iso_path: "{{ path }}"
      esxi:
        hostname: "{{ esxi_hostname }}"
        datacenter: "{{ esxi_datacenter }}"
