# DeployWindowsClient.yml - A playbook that deploys a Windows 7 client in VCSA.
---
- hosts: localhost
  tasks:
  - name: Deploy the Windows client
    vsphere_guest:
      vcenter_hostname: vcenter.rit.test
      username: administrator@vsphere.local
      password: P@ssw0rd123
      guest: "Windows 7 Client"
      state: powered_on
      vm_disk:
        disk1:
          size_gb: 80
          type: thin
          datastore: datastore3
          folder: "Windows 7 Client"
      vm_nic:
        nic1:
          type: e1000
          network: "VM Network"
          network_type: standard
      vm_hardware:
        memory_mb: 2048
        num_cpus: 1
        osid: windows7_64guest
        scsi: "lsi_sas"
        vm_cdrom:
          type: "iso"
          iso_path: datastore3/Win7SP1Unattend.iso
      esxi:
        hostname: esxi03.rit.test
        datacenter: Datacenter
