# InstallActiveDirectory.yml - Install Active Directory Domain Services.
---
- hosts: windows-dc
  remote_user: Administrator
  tasks:
    - name: Install AD DS.
      win_feature:
        name: AD-Domain-Services
        include_management_tools: True
        state: present
    - name: Reboot the machine.
      win_reboot:
