# JoinDomain.yml - Joins the Windows client to the test domain.
---
- hosts: windows-client
  tasks:
    - name: Point DNS at correct DNS server
      win_dns_client:
        adapter_names: "Local Area Connection"
        ipv4_addresses: 10.80.100.7
    - name: Join client to the rit.test domain
      win_domain_membership:
        dns_domain_name: rit.test
        hostname: client
        domain_admin_user: Administrator@rit.test
        domain_admin_password: P@ssw0rd123
        state: domain
      register: domain_state
    - name: Reboot client if necessary
      win_reboot:
      when: domain_state.reboot_required
